name: Release test

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: openjdk@1.14
