name: Release pensjon-samhandling-ktor-support

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: openjdk@1.14

      - name: Change gradlew permissions to executable
        run: chmod +x ./gradlew

      - name: Test Build
        run: ./gradlew test build
        #env:
        #  ORG_GRADLE_PROJECT_githubUser: x-access-token
        #  ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

      - name: capture version number for release
        run: echo "::set-env name=VERSION::$(grep -v '^#' gradle.properties | grep 'version=' | cut -d '=' -f2 | xargs)"

      - name: build and update version
        run: ./gradlew build release -Prelease.useAutomaticVersion=true

      - name: check out release-version
        uses: actions/checkout@v2
        with:
          ref: "release-${{ env.VERSION }}"

      - name: publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}